# Phase 4 - Feature Engineering

In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv("../data1/Telco-Customer-Churn.csv")

In [3]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 21 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   customerID        7043 non-null   str
 1   gender            7043 non-null   str
 2   SeniorCitizen     7043 non-null   int64
 3   Partner           7043 non-null   str
 4   Dependents        7043 non-null   str
 5   tenure            7043 non-null   int64
 6   PhoneService      7043 non-null   str
 7   MultipleLines     7043 non-null   str
 8   InternetService   7043 non-null   str
 9   OnlineSecurity    7043 non-null   str
 10  OnlineBackup      7043 non-null   str
 11  DeviceProtection  7043 non-null   str
 12  TechSupport       7043 non-null   str
 13  StreamingTV       7043 non-null   str
 14  StreamingMovies   7043 non-null   str
 15  Contract          7043 non-null   str
 16  PaperlessBilling  7043 non-null   str
 17  PaymentMethod     7043 non-null   str
 18  MonthlyCharges    7043 non-null   float64
 19  TotalCharges      7043 non-null   str
 20  Churn             7043 non-null   str
dtypes: float64(1), int64(2), str(18)
memory usage: 1.9 MB

In [4]:
df.head()

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,7590-VHVEG,Female,0,Yes,No,1,No,No phone service,DSL,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No
1,5575-GNVDE,Male,0,No,No,34,Yes,No,DSL,Yes,...,Yes,No,No,No,One year,No,Mailed check,56.95,1889.5,No
2,3668-QPYBK,Male,0,No,No,2,Yes,No,DSL,Yes,...,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes
3,7795-CFOCW,Male,0,No,No,45,No,No phone service,DSL,Yes,...,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No
4,9237-HQITU,Female,0,No,No,2,Yes,No,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes

In [5]:
df = df.drop("customerID", axis=1)

In [6]:
df.head()

,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,OnlineBackup,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,Female,0,Yes,No,1,No,No phone service,DSL,No,Yes,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No
1,Male,0,No,No,34,Yes,No,DSL,Yes,No,Yes,No,No,No,One year,No,Mailed check,56.95,1889.5,No
2,Male,0,No,No,2,Yes,No,DSL,Yes,Yes,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes
3,Male,0,No,No,45,No,No phone service,DSL,Yes,No,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No
4,Female,0,No,No,2,Yes,No,Fiber optic,No,No,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes

### Observation

- CustomerID is a unique identifier.
- It does not contain predictive information.
- Therefore, it has been removed before model training.

In [7]:
df.columns

Index(['gender', 'SeniorCitizen', 'Partner', 'Dependents', 'tenure',
       'PhoneService', 'MultipleLines', 'InternetService', 'OnlineSecurity',
       'OnlineBackup', 'DeviceProtection', 'TechSupport', 'StreamingTV',
       'StreamingMovies', 'Contract', 'PaperlessBilling', 'PaymentMethod',
       'MonthlyCharges', 'TotalCharges', 'Churn'],
      dtype='str')

In [8]:
from sklearn.preprocessing import LabelEncoder

In [9]:
le = LabelEncoder()

In [10]:
binary_cols = [
    "gender",
    "Partner",
    "Dependents",
    "PhoneService",
    "PaperlessBilling",
    "Churn"
]

In [11]:
for col in binary_cols:
    df[col] = le.fit_transform(df[col])

In [12]:
df.head()

,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,OnlineBackup,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,0,0,1,0,1,0,No phone service,DSL,No,Yes,No,No,No,No,Month-to-month,1,Electronic check,29.85,29.85,0
1,1,0,0,0,34,1,No,DSL,Yes,No,Yes,No,No,No,One year,0,Mailed check,56.95,1889.5,0
2,1,0,0,0,2,1,No,DSL,Yes,Yes,No,No,No,No,Month-to-month,1,Mailed check,53.85,108.15,1
3,1,0,0,0,45,0,No phone service,DSL,Yes,No,Yes,Yes,No,No,One year,0,Bank transfer (automatic),42.30,1840.75,0
4,0,0,0,0,2,1,No,Fiber optic,No,No,No,No,No,No,Month-to-month,1,Electronic check,70.70,151.65,1

In [13]:
df[binary_cols].head()

   gender  Partner  Dependents  PhoneService  PaperlessBilling  Churn
0       0        1           0             0                 1      0
1       1        0           0             1                 0      0
2       1        0           0             1                 1      1
3       1        0           0             0                 0      0
4       0        0           0             1                 1      1

## Label Encoding

### Observation

Binary categorical variables were converted into numerical values using Label Encoding.

Encoding applied:

- Female → 0, Male → 1
- No → 0, Yes → 1

This conversion allows machine learning algorithms to process categorical information while preserving the binary relationship between values.

In [14]:
multi_cols = [
    "MultipleLines",
    "InternetService",
    "OnlineSecurity",
    "OnlineBackup",
    "DeviceProtection",
    "TechSupport",
    "StreamingTV",
    "StreamingMovies",
    "Contract",
    "PaymentMethod"
]

In [15]:
df = pd.get_dummies(
    df,
    columns=multi_cols,
    drop_first=True,
    dtype=int
)

In [16]:
df.head()

,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,PaperlessBilling,MonthlyCharges,TotalCharges,Churn,...,TechSupport_Yes,StreamingTV_No internet service,StreamingTV_Yes,StreamingMovies_No internet service,StreamingMovies_Yes,Contract_One year,Contract_Two year,PaymentMethod_Credit card (automatic),PaymentMethod_Electronic check,PaymentMethod_Mailed check
0,0,0,1,0,1,0,1,29.85,29.85,0,...,0,0,0,0,0,0,0,0,1,0
1,1,0,0,0,34,1,0,56.95,1889.5,0,...,0,0,0,0,0,1,0,0,0,1
2,1,0,0,0,2,1,1,53.85,108.15,1,...,0,0,0,0,0,0,0,0,0,1
3,1,0,0,0,45,0,0,42.30,1840.75,0,...,1,0,0,0,0,1,0,0,0,0
4,0,0,0,0,2,1,1,70.70,151.65,1,...,0,0,0,0,0,0,0,0,1,0

In [17]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 31 columns):
 #   Column                                 Non-Null Count  Dtype
---  ------                                 --------------  -----
 0   gender                                 7043 non-null   int64
 1   SeniorCitizen                          7043 non-null   int64
 2   Partner                                7043 non-null   int64
 3   Dependents                             7043 non-null   int64
 4   tenure                                 7043 non-null   int64
 5   PhoneService                           7043 non-null   int64
 6   PaperlessBilling                       7043 non-null   int64
 7   MonthlyCharges                         7043 non-null   float64
 8   TotalCharges                           7043 non-null   str
 9   Churn                                  7043 non-null   int64
 10  MultipleLines_No phone service         7043 non-null   int64
 11  MultipleLines_Yes                      7043 non-null   int64
 12  InternetService_Fiber optic            7043 non-null   int64
 13  InternetService_No                     7043 non-null   int64
 14  OnlineSecurity_No internet service     7043 non-null   int64
 15  OnlineSecurity_Yes                     7043 non-null   int64
 16  OnlineBackup_No internet service       7043 non-null   int64
 17  OnlineBackup_Yes                       7043 non-null   int64
 18  DeviceProtection_No internet service   7043 non-null   int64
 19  DeviceProtection_Yes                   7043 non-null   int64
 20  TechSupport_No internet service        7043 non-null   int64
 21  TechSupport_Yes                        7043 non-null   int64
 22  StreamingTV_No internet service        7043 non-null   int64
 23  StreamingTV_Yes                        7043 non-null   int64
 24  StreamingMovies_No internet service    7043 non-null   int64
 25  StreamingMovies_Yes                    7043 non-null   int64
 26  Contract_One year                      7043 non-null   int64
 27  Contract_Two year                      7043 non-null   int64
 28  PaymentMethod_Credit card (automatic)  7043 non-null   int64
 29  PaymentMethod_Electronic check         7043 non-null   int64
 30  PaymentMethod_Mailed check             7043 non-null   int64
dtypes: float64(1), int64(29), str(1)
memory usage: 1.7 MB

## One-Hot Encoding

### Observation

Categorical columns having more than two categories were transformed using One-Hot Encoding.

The first category was dropped (`drop_first=True`) to avoid the Dummy Variable Trap and reduce multicollinearity.

After encoding, all features became numerical and suitable for machine learning algorithms.

In [18]:
df["TotalCharges"] = pd.to_numeric(df["TotalCharges"], errors="coerce")

In [19]:
df = df.dropna()

In [20]:
df.info()

<class 'pandas.DataFrame'>
Index: 7032 entries, 0 to 7042
Data columns (total 31 columns):
 #   Column                                 Non-Null Count  Dtype
---  ------                                 --------------  -----
 0   gender                                 7032 non-null   int64
 1   SeniorCitizen                          7032 non-null   int64
 2   Partner                                7032 non-null   int64
 3   Dependents                             7032 non-null   int64
 4   tenure                                 7032 non-null   int64
 5   PhoneService                           7032 non-null   int64
 6   PaperlessBilling                       7032 non-null   int64
 7   MonthlyCharges                         7032 non-null   float64
 8   TotalCharges                           7032 non-null   float64
 9   Churn                                  7032 non-null   int64
 10  MultipleLines_No phone service         7032 non-null   int64
 11  MultipleLines_Yes                      7032 non-null   int64
 12  InternetService_Fiber optic            7032 non-null   int64
 13  InternetService_No                     7032 non-null   int64
 14  OnlineSecurity_No internet service     7032 non-null   int64
 15  OnlineSecurity_Yes                     7032 non-null   int64
 16  OnlineBackup_No internet service       7032 non-null   int64
 17  OnlineBackup_Yes                       7032 non-null   int64
 18  DeviceProtection_No internet service   7032 non-null   int64
 19  DeviceProtection_Yes                   7032 non-null   int64
 20  TechSupport_No internet service        7032 non-null   int64
 21  TechSupport_Yes                        7032 non-null   int64
 22  StreamingTV_No internet service        7032 non-null   int64
 23  StreamingTV_Yes                        7032 non-null   int64
 24  StreamingMovies_No internet service    7032 non-null   int64
 25  StreamingMovies_Yes                    7032 non-null   int64
 26  Contract_One year                      7032 non-null   int64
 27  Contract_Two year                      7032 non-null   int64
 28  PaymentMethod_Credit card (automatic)  7032 non-null   int64
 29  PaymentMethod_Electronic check         7032 non-null   int64
 30  PaymentMethod_Mailed check             7032 non-null   int64
dtypes: float64(2), int64(29)
memory usage: 1.7 MB

In [21]:
df.head()

,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,PaperlessBilling,MonthlyCharges,TotalCharges,Churn,...,TechSupport_Yes,StreamingTV_No internet service,StreamingTV_Yes,StreamingMovies_No internet service,StreamingMovies_Yes,Contract_One year,Contract_Two year,PaymentMethod_Credit card (automatic),PaymentMethod_Electronic check,PaymentMethod_Mailed check
0,0,0,1,0,1,0,1,29.85,29.85,0,...,0,0,0,0,0,0,0,0,1,0
1,1,0,0,0,34,1,0,56.95,1889.50,0,...,0,0,0,0,0,1,0,0,0,1
2,1,0,0,0,2,1,1,53.85,108.15,1,...,0,0,0,0,0,0,0,0,0,1
3,1,0,0,0,45,0,0,42.30,1840.75,0,...,1,0,0,0,0,1,0,0,0,0
4,0,0,0,0,2,1,1,70.70,151.65,1,...,0,0,0,0,0,0,0,0,1,0

In [22]:
from sklearn.model_selection import train_test_split

In [23]:
X = df.drop("Churn", axis=1)
y = df["Churn"]

In [24]:
print(X.shape)
print(y.shape)

(7032, 30)
(7032,)

In [25]:
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.20,
    random_state=42

)

In [26]:
print("X_train:", X_train.shape)
print("X_test :", X_test.shape)
print("y_train:", y_train.shape)
print("y_test :", y_test.shape)

X_train: (5625, 30)
X_test : (1407, 30)
y_train: (5625,)
y_test : (1407,)

In [27]:
from sklearn.preprocessing import StandardScaler

In [28]:
scaler = StandardScaler()

In [29]:
X_train = scaler.fit_transform(X_train)

In [30]:
X_test = scaler.transform(X_test)

In [31]:
print(X_train[:5])

[[-1.01378388 -0.43758982 -0.9624811  -0.65368396  0.43467403 -3.04070742
   0.83139683 -0.51862031 -0.08790784  3.04070742 -0.84554067 -0.88544634
  -0.52984687 -0.52984687 -0.63517172 -0.52984687 -0.7281455  -0.52984687
   1.38474948 -0.52984687 -0.63875661 -0.52984687  1.26181056 -0.52984687
   1.2472596  -0.51827235 -0.5611299  -0.52764485 -0.71475753 -0.54742719]
 [ 0.98640353 -0.43758982 -0.9624811  -0.65368396 -1.19565249  0.32887084
  -1.20279506 -0.3744434  -0.92128463 -0.32887084 -0.84554067 -0.88544634
  -0.52984687 -0.52984687 -0.63517172 -0.52984687 -0.7281455  -0.52984687
  -0.72215228 -0.52984687 -0.63875661 -0.52984687  1.26181056 -0.52984687
  -0.80175771 -0.51827235 -0.5611299   1.89521417 -0.71475753 -0.54742719]
 [-1.01378388 -0.43758982  1.03898144 -0.65368396  0.92377199  0.32887084
   0.83139683  0.43261589  0.96378055 -0.32887084  1.18267522  1.12937391
  -0.52984687 -0.52984687 -0.63517172 -0.52984687 -0.7281455  -0.52984687
   1.38474948 -0.52984687 -0.63875661 -0.52984687 -0.79251199 -0.52984687
  -0.80175771 -0.51827235 -0.5611299  -0.52764485  1.39907586 -0.54742719]
 [ 0.98640353 -0.43758982  1.03898144  1.52979125  0.51619036  0.32887084
  -1.20279506 -0.33301325  0.12291993 -0.32887084 -0.84554067 -0.88544634
  -0.52984687 -0.52984687  1.5743774  -0.52984687 -0.7281455  -0.52984687
  -0.72215228 -0.52984687  1.56554152 -0.52984687 -0.79251199 -0.52984687
  -0.80175771 -0.51827235  1.78211856 -0.52764485 -0.71475753 -0.54742719]
 [-1.01378388 -0.43758982  1.03898144  1.52979125  0.92377199  0.32887084
  -1.20279506  1.19990224  1.40108812 -0.32887084  1.18267522  1.12937391
  -0.52984687 -0.52984687  1.5743774  -0.52984687 -0.7281455  -0.52984687
  -0.72215228 -0.52984687 -0.63875661 -0.52984687  1.26181056 -0.52984687
   1.2472596   1.92948747 -0.5611299  -0.52764485 -0.71475753  1.82672696]]

## Feature Scaling

### Observation

The numerical features were standardized using StandardScaler.

- The scaler was fitted only on the training data.
- The same transformation was applied to the testing data.
- This prevents data leakage and ensures fair model evaluation.